/** Tokens de diseño extraídos de Desing/stitch_ingenieria_sol_service_portal (los 6 mockups + DESIGN.md). */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'surface-dim': '#cbdbf5',
        'surface-tint': '#565e74',
        'on-surface': '#0b1c30',
        'on-background': '#0b1c30',
        'on-surface-variant': '#45464d',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',

        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#131b2e',
        'on-primary-container': '#7c839b',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',

        secondary: '#9d4300',
        'on-secondary': '#ffffff',
        'secondary-container': '#fd761a',
        'on-secondary-container': '#5c2400',
        'secondary-fixed': '#ffdbca',
        'secondary-fixed-dim': '#ffb690',
        'on-secondary-fixed': '#341100',
        'on-secondary-fixed-variant': '#783200',

        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#002113',
        'on-tertiary-container': '#009668',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#bec6e0',
      },
      // Ojo: estos nombres (xs/sm/md/lg/xl) tambien son usados internamente
      // por la escala de max-w-*, y en Tailwind v4 spacing tiene prioridad
      // sobre ese valor por defecto. Por eso max-w-sm/md/lg/xl NO deben
      // usarse en este proyecto: usar max-w-[Nrem] (valor arbitrario) en su lugar.
      spacing: {
        base: '0.4rem',
        xs: '0.4rem',
        sm: '0.8rem',
        md: '1.6rem',
        lg: '2.4rem',
        xl: '3.2rem',
        gutter: '1.6rem',
        'margin-mobile': '1.6rem',
        'margin-desktop': '3.2rem',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['"JetBrains Mono"', 'monospace'],
        'label-sm': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['4.8rem', { lineHeight: '5.6rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['3.2rem', { lineHeight: '4.0rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['2.4rem', { lineHeight: '3.2rem', fontWeight: '600' }],
        'headline-md': ['2.4rem', { lineHeight: '3.2rem', fontWeight: '600' }],
        'body-lg': ['1.8rem', { lineHeight: '2.8rem', fontWeight: '400' }],
        'body-md': ['1.6rem', { lineHeight: '2.4rem', fontWeight: '400' }],
        'body-sm': ['1.4rem', { lineHeight: '2.0rem', fontWeight: '400' }],
        'label-md': ['1.4rem', { lineHeight: '1.6rem', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['1.2rem', { lineHeight: '1.6rem', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
}
